dbt_project:
  name: 'reddit_pipeline'
  version: '1.0.0'
  config-version: 2
  
  profile: 'reddit_pipeline'
  
  model-paths: ["models"]
  analysis-paths: ["analysis"]
  test-paths: ["tests"]
  data-paths: ["data"]
  macro-paths: ["macros"]
  snapshot-paths: ["snapshots"]
  target-path: "target"
  clean-targets:
    - "target"
    - "dbt_packages"

  models:
    reddit_pipeline:
      staging:
        +materialized: view
      marts:
        +materialized: table
