apiVersion: 1

datasources:
  - name: PostgreSQL Reddit Pipeline
    type: postgres
    isDefault: true
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: SecurePostgresPass2024
    jsonData:
      database: reddit_pipeline
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
