apiVersion: 1

datasources:
  - name: PostgreSQL Reddit Pipeline
    type: postgres
    access: proxy
    isDefault: true
    host: postgres
    port: 5432
    database: reddit_pipeline
    user: postgres
    password: SecurePostgresPass2024
    jsonData:
      sslmode: disable
